<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tap_payment_transactions', function (Blueprint $table) {
            $table->id();
            $table->string('transaction_id')->unique()->comment('Unique transaction ID generated by our system');
            $table->string('charge_id')->nullable()->comment('Charge ID returned by Tap Payments');
            $table->string('token_id')->nullable()->comment('Token ID returned by Tap Payments');
            $table->decimal('amount', 10, 3)->comment('Transaction amount');
            $table->string('currency', 3)->default('KWD')->comment('Transaction currency');
            $table->string('description')->nullable()->comment('Transaction description');
            $table->string('reference_id')->nullable()->comment('External reference ID');
            $table->string('customer_name')->nullable()->comment('Customer name');
            $table->string('customer_email')->nullable()->comment('Customer email');
            $table->string('customer_phone')->nullable()->comment('Customer phone');
            $table->string('payment_method')->default('APPLEPAY')->comment('Payment method used');
            $table->string('card_brand')->nullable()->comment('Card brand (VISA, MASTERCARD, etc.)');
            $table->string('card_last_four')->nullable()->comment('Last four digits of the card');
            $table->string('status')->default('pending')->comment('Transaction status (pending, successful, failed)');
            $table->json('request_payload')->nullable()->comment('Full request payload sent to Tap Payments');
            $table->json('response_payload')->nullable()->comment('Full response payload received from Tap Payments');
            $table->json('webhook_payload')->nullable()->comment('Webhook payload received from Tap Payments');
            $table->string('error_code')->nullable()->comment('Error code if transaction failed');
            $table->string('error_message')->nullable()->comment('Error message if transaction failed');
            $table->string('ip_address')->nullable()->comment('Customer IP address');
            $table->foreignId('user_id')->nullable()->constrained()->onDelete('set null')->comment('User who initiated the transaction');
            $table->timestamps();
            $table->index(['transaction_id', 'charge_id', 'status']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tap_payment_transactions');
    }
};
